main: dev.skyphi.KillGoal
name: KillGoal
version: 1.2.3
api-version: 1.20
depend: [ProtocolLib]
commands:
  setgoal:
    description: Set the server-wide kill goal
    usage: /<command> <number>
    default: op
  leaderboard:
    description: Set the leaderboard at your position
    usage: /<command> [numPlayers]
    default: op