main: dev.skyphi.KillGoal
name: KillGoal
version: 1.1
api-version: 1.20
depend: [ProtocolLib]
commands:
  setgoal:
    description: Set the server-wide kill goal
    usage: /<command> <number>
  leaderboard:
    description: Set the leaderboard at your position
    usage: /<command> [numPlayers]